pub mod batch;
pub mod comments;
pub mod file_order;
pub mod graphics;
pub mod index;
pub mod line_edit;
pub mod link_audit;
pub mod locations;
pub mod markdown;
pub mod markdown_edit;
pub mod performance;
pub mod preferences;
pub mod preview;
pub mod properties;
pub mod rendering;
pub mod search;
pub mod syntax;
pub mod tables;
pub mod tags;
pub mod text_changes;
pub mod updates;
pub mod vault;
pub mod word_count;
mod yaml_source;

pub mod startup_trace;
