[package]
name = "inkstone-desktop"
default-run = "inkstone"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "inkstone"
path = "src/main.rs"

[dependencies]
inkstone-core.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-base.workspace = true
gpui-kit.workspace = true
serde_json.workspace = true
notify.workspace = true
markdown-parser.workspace = true
anyhow.workspace = true
lsp-types.workspace = true
percent-encoding.workspace = true
regex.workspace = true
chrono.workspace = true
similar.workspace = true
sha2.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-foundation.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
ropey.workspace = true
unicode-segmentation.workspace = true
